Found 'cute' with frequency 10
Delete 'cute' succeeded
NOT Found 'cute'
NOT Found 'book'
Add 'book' succeeded
Found 'book' with frequency 10000
Found 'apple' with frequency 300
Delete 'apple' succeeded
NOT Found 'apple'
Delete 'apple' failed
Autocomplete for 'c': [ calm: 1000  cuts: 50  cut: 30  ]
Autocomplete for 'cut': [ cuts: 50  cut: 30  ]
Autocomplete for 'farms': [ ]
Delete 'cut' succeeded
Autocomplete for 'cut': [ cuts: 50  ]
